lab02/encuesta/urls.py
from django.urls import path

from . import views

app_name='encuesta'

urlpatterns = [
    #path('', views.index,name='index'),
    #path('enviar', views.enviar,name='enviar'),
    
    #path('', views.indexmatematico,name='indexmatematico'),
    #path('enviar2', views.enviar2,name='enviar2'),
    
    path('', views.indexcilindro,name='indexcilindro'),
    path('calcular', views.calcular,name='calcular'),
   
]

lab02/lab02/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('encuesta/',include('encuesta.urls')),
    path('admin/', admin.site.urls),
]

lab02/encuesta/models.py
from django.db import models

# Create your models here.

lab02/encuesta/views.py
from django.shortcuts import render

# Creacion de vistas.
def index(request):
    context = {
        'titulo':"Formulaario"
    }
    return render(request, 'encuesta/formulario.html', context)


#-----------------------------Vista formulario matematico---------------------------
def indexmatematico(request):
    context = {
        'titulo':"Formulaario"
    }
    return render(request, 'encuesta/formatematico.html', context)

#-----------------------------Vista formulario de Cilindro---------------------------
def indexcilindro(request):
    context = {
        'titulo':"Formulario de Volumen"
    }
    return render(request, 'encuesta/forcilindro.html', context)


def enviar(request):
    context = {
        'titulo': "Respuesta",
        'nombre': request.POST['nombre'], #request.POST['nombre'] etiqueta name="nombre"
        'clave': request.POST['password'], #clave biene ser las variables que van aser usadas
        'educacion': request.POST['educacion'],
        'nacionalidad': request.POST['nacionalidad'],
        'idiomas': request.POST.getlist('idiomas'),
        'correo': request.POST['email'],
        'website': request.POST['sitioweb'],     
    }
    return render(request,'encuesta/respuesta.html', context )  #manda valores de la funcion hacia respuesta.html



def enviar2(request):
    x = request.POST['number1']
    y = request.POST['number2']
    
    resultsuma = int(x) + int(y) 
    resultresta = int(x) - int(y)
    resultmulti = int(x) * int(y)
    
    context = {
        'titulo': "Respuesta",
        'numero1': request.POST['number1'], #request.POST['number1'] etiqueta name="number1"
        'numero2': request.POST['number2'], #clave biene ser las variables que van aser usadas
        'operacion': request.POST['operacion'],
        'suma': resultsuma,
        'resta': resultresta,
        'multi': resultmulti,     
    }
    return render(request,'encuesta/resmatematico.html', context )


def calcular(request):
    x = request.POST['diametro']
    radio2 = ((float(x) / 2) ** 2) * 3.1416
    
    y = request.POST['altura']
    
    resultvolumen = float(radio2) * float(y) 
    #resultresta = int(x) - int(y)
    #resultmulti = int(x) * int(y)
    
    context1 = {
        'titulo': "Formulario de Volumen:",
        #'numero1': request.POST['number1'], #request.POST['number1'] etiqueta name="number1"
        #'numero2': request.POST['number2'], #clave biene ser las variables que van aser usadas
        #'operacion': request.POST['operacion'],
        'volumen': resultvolumen,
        #'radio': radio2,
        
            
    }
    return render(request,'encuesta/forcilindro.html', context1 )

lab02/encuesta/templates/encuesta/forcilindro.html
<form action="{% url 'encuesta:calcular' %}" method="post"> 
    {% csrf_token %}

    <h1>{{titulo}}</h1>
    Introduzaca el diametro en metros:
    <input type="number" name="diametro" step="0.001" ><br>
    Introduzaca la altura en metros:
    <input type="number" name="altura" step="0.001" ><br>
  
    // Boton de calcular
    <input type="submit" name="submit" value="Calcular">

</form>



<p>
    {% if volumen %}
    <p>Respuesta:</p>
    <p> <em>El volumen del cilindro es de </em> {{ volumen }} <em>metros cubicos</em>  </p>
    {% endif %}
</p>

lab02/encuesta/templates/encuesta/formatematico.html
<h2>{{titulo}}</h2>

<form action="{% url 'encuesta:enviar2' %}" method="post"> 

    {% csrf_token %}

    <h1>Operaciones Matematicas</h1>
    Ingrese un numero:
    <input type="number" name="number1" ><br>
    Ingrese otro numero:
    <input type="number" name="number2" ><br>
    Seleccione la Operacion a realizar:
    <select name="operacion" id="">
        <option value="suma">Sumar</option>
        <option value="operacion-obligatoria" selected="selected">Operacion Obligatoria</option>
        <option value="resta">Restar</option>
        <option value="multi">Multiplicar</option>
    </select><br>
    // Boton de enviar
    <input type="submit" name="submit" value="Enviar">
</form>

lab02/encuesta/templates/encuesta/formulario.html
<h2>{{ titulo }}</h2>
<form action="{% url 'encuesta:enviar' %" method="post">
    {% csrf_token %}
    Nombre:
    <input type="text" name="nombre" maxlength="50"><br>
    Contraseña:
    <input type="password" name="password"><br>
    Educación:
    <select name="educacion">
        <option value="sin-estudios">Sin Estudios</option>
        <option value="educacion-obligatoria">Educacion Obligatoria</option>
        <option value="formacion-profesional">Formacion Profesional</option>
        <option value="universidad">Universidad</option>
    </select><br>
    Nacionalidad:
    <input type="radio" name="nacionalidad" value="Peruana">Peruana</input>
    <input type="radio" name="nacionalidad" value="Otra">Otra</input><br>
    Idiomas:
    <input type="checkbox" name="idiomas" value="español" checked="checked">Español</input>
    <input type="checkbox" name="idiomas" value="ingles" >Ingles</input>
    <input type="checkbox" name="idiomas" value="frances" >Frances</input>
    <input type="checkbox" name="idiomas" value="aleman" >Aleman</input><br>
    Email:
    <input type="text" name="email"><br>
    Sitio Web:
    <input type="text" name="sitioweb"><br>
    <input type="submit" name="submit" value="Enviar">
</form>

lab02/encuesta/templates/encuesta/resmatematico.html
<h2>{{ titulo }}</h2>

<p>Primer valor: {{ numero1 }}</p>
<p>Segundo valor: {{ numero2 }}</p>

<p>
    
    {% if operacion == "suma" %}
        <p>Se ha selecionado la operacion Sumar</p>
        <p> <em>La suma de </em> {{ numero1 }} <em>+</em> {{ numero2}} <em>=</em> {{ suma}} </p>
    {% endif %}

    {% if operacion == "resta" %}
        <p>Se ha selecionado la operacion Restar</p>
        <p> <em>La resta de </em> {{ numero1 }} <em>-</em> {{ numero2}} <em>=</em> {{ resta}}  </p>        
    {% endif %}

    {% if operacion == "multi" %}
        <p>Se ha selecionado la operacion Multiplicar</p>
        <p> <em>La multiplicacion de </em> {{ numero1 }} <em>*</em> {{ numero2}} <em>=</em> {{ multi}}  </p>        
    {% endif %}

</p>

lab02/encuesta/templates/encuesta/respuesta.html
<h2>{{titulo}}</h2>
<p>Nombre: {{nombre}}</p>
<p>Clave: {{clave}}</p>
<p>Educación: {{educacion}}</p>
<p>Nacionalidad: {{nacionalidad}}</p>
<p>Idiomas:</p>
<ul>
    {% for item in idiomas %}
        <li>{{item}}</li>
    {% endfor %}
</ul>
<p>Email: {{correo}}</p>
<p>Sitio web: {{website}}</p>